name: Actions

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Run composer install
        run: composer install
      - name: Run npm install
        run: npm install
      - name: Run npm run dev
        run: npm run dev
      - name: Create .env
        run: cp .env.example .env
      - name: Create app key
        run: php artisan key:generate
      - name: Run tests
        run: ./vendor/bin/phpunit
        env:
          APP_ENV: testing
